"""
Narrative synthesis. This is where an LLM call slots in. If ANTHROPIC_API_KEY
is set, we ask Claude to write the brief's narrative from the structured data.
If not (or the SDK isn't installed), we fall back to a deterministic template
so the chassis always runs. Either way the agent gets back (narrative, cost).
"""
from __future__ import annotations

from app.config import get_settings


def synthesize_brief(structured: dict, org_name: str) -> tuple[str, float]:
    settings = get_settings()
    if settings.anthropic_api_key:
        try:
            return _llm_narrative(structured, org_name, settings)
        except Exception:  # never let synthesis crash a run; fall back
            pass
    return _template_narrative(structured, org_name), 0.0


def _llm_narrative(structured: dict, org_name: str, settings) -> tuple[str, float]:
    import anthropic

    client = anthropic.Anthropic(api_key=settings.anthropic_api_key)
    prompt = (
        f"You are a demand-gen analyst writing a weekly market brief for {org_name}. "
        f"Using ONLY the structured findings below, write a tight, skimmable brief "
        f"(sizing takeaway, top targets, what the market is searching, recommended "
        f"channels and content angles). Do not invent numbers.\n\n"
        f"FINDINGS:\n{structured}"
    )
    msg = client.messages.create(
        model=settings.anthropic_model,
        max_tokens=1200,
        messages=[{"role": "user", "content": prompt}],
    )
    text = "".join(b.text for b in msg.content if getattr(b, "type", "") == "text")
    usage = getattr(msg, "usage", None)
    cost = 0.0
    if usage:
        cost = (usage.input_tokens * 3 + usage.output_tokens * 15) / 1_000_000
    return text, round(cost, 6)


def _template_narrative(s: dict, org_name: str) -> str:
    sizing = s["sizing"]
    targets = s["top_targets"][:5]
    kw = s["keyword_clusters"]
    lines = [
        f"# Weekly market brief — {org_name}",
        "",
        "## Market size",
        f"- TAM: {sizing['tam_companies']:,} addressable companies "
        f"(~${sizing['tam_revenue_usd']/1e9:,.1f}B aggregate revenue)",
        f"- SAM: {sizing['sam_companies']:,} companies match the addressable ICP filters",
        f"- SOM (modeled): {sizing['som_companies']:,} realistically winnable this year",
        "",
        "## Top target accounts (fit × intent)",
    ]
    for t in targets:
        lines.append(
            f"- {t['name']} — {t['industry']}, {t['employees']:,} employees · "
            f"fit {t['fit_score']:.0%}, intent {t['intent_score']:.0%}"
        )
    lines += ["", "## What the market is searching"]
    for cluster, terms in kw.items():
        head = ", ".join(t["term"] for t in terms[:3])
        lines.append(f"- {cluster.title()} intent: {head} …")
    lines += ["", "## Recommended next moves", "- " + "\n- ".join(s["recommendations"])]
    lines.append("")
    lines.append("_(Narrative generated by deterministic template — set "
                 "ANTHROPIC_API_KEY to have Claude write this section.)_")
    return "\n".join(lines)
